# Generated by Django 6.0.7 on 2026-08-03 05:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=45, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=13)),
                ('profile_pic', models.ImageField(default='', upload_to='user_pic')),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
