# Generated by Django 6.0.7 on 2026-08-08 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0004_creatordetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatordetail',
            name='profile_pic',
            field=models.ImageField(default='', upload_to='creatorpic/'),
        ),
        migrations.CreateModel(
            name='RecipeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(max_length=10)),
                ('recipe_name', models.CharField(max_length=150)),
                ('recipe_category', models.CharField(max_length=100)),
                ('ingredients', models.TextField()),
                ('recipe_video', models.FileField(upload_to='recipe_videos/')),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.creatordetail')),
            ],
        ),
    ]
