# Generated by Django 6.0.7 on 2026-08-08 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0005_alter_creatordetail_profile_pic_recipevideo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipevideo',
            old_name='whatsapp_number',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='recipevideo',
            name='recipe_name',
        ),
        migrations.AddField(
            model_name='recipevideo',
            name='name',
            field=models.CharField(default=datetime.datetime(2026, 8, 8, 16, 12, 37, 597770, tzinfo=datetime.timezone.utc), max_length=150),
            preserve_default=False,
        ),
    ]
