# Generated by Django 6.0.7 on 2026-08-13 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0006_rename_whatsapp_number_recipevideo_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatordetail',
            name='profile_pic',
            field=models.ImageField(default='', upload_to='creatorpic'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
                ('product_name', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.CharField(max_length=20)),
                ('product_pic', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.creatordetail')),
            ],
        ),
    ]
