# Generated by Django 6.1.1 on 2026-09-14 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0011_repair_creator_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatordetail',
            name='delivery_radius_km',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='creatordetail',
            name='response_time_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='product',
            name='batch_code',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='best_before_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='product',
            name='creator_choice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_homemade',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='prepared_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipevideo',
            name='servings',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.CreateModel(
            name='CreatorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_reviews', to='project_app.creatordetail')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_reviews', to='project_app.userdetail')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('New', 'New'), ('Replied', 'Replied'), ('Resolved', 'Resolved'), ('Archived', 'Archived')], default='New', max_length=20)),
                ('reply', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries_received', to='project_app.creatordetail')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='project_app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries_sent', to='project_app.userdetail')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_note', models.CharField(blank=True, default='', max_length=250)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Preparing', 'Preparing'), ('Ready', 'Ready'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_requests_received', to='project_app.creatordetail')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_requests', to='project_app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_requests', to='project_app.userdetail')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=150)),
                ('quantity', models.CharField(blank=True, default='', max_length=80)),
                ('is_purchased', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_items', to='project_app.recipevideo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_items', to='project_app.userdetail')),
            ],
            options={
                'ordering': ['is_purchased', 'ingredient'],
            },
        ),
    ]
