# Generated by Django 6.1.1
import uuid

from django.db import migrations, models


def generate_order_code():
    return f"FC-{uuid.uuid4().hex[:10].upper()}"


def _populate_order_codes(apps, schema_editor):
    order_model = apps.get_model("project_app", "OrderRequest")
    for order in order_model.objects.filter(order_code=""):
        order.order_code = generate_order_code()
        order.save(update_fields=["order_code"])


class Migration(migrations.Migration):
    dependencies = [
        ("project_app", "0012_creatordetail_delivery_radius_km_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderrequest",
            name="order_code",
            field=models.CharField(default="", editable=False, max_length=18),
        ),
        migrations.AddField(
            model_name="orderrequest",
            name="payment_method",
            field=models.CharField(choices=[("COD", "Cash on Delivery"), ("UPI", "UPI")], default="COD", max_length=10),
        ),
        migrations.AddField(
            model_name="orderrequest",
            name="payment_status",
            field=models.CharField(choices=[("Submitted", "Submitted"), ("Verified", "Verified"), ("Rejected", "Rejected")], default="Submitted", max_length=12),
        ),
        migrations.AddField(
            model_name="orderrequest",
            name="payment_screenshot",
            field=models.ImageField(blank=True, null=True, upload_to="payment_screenshots/"),
        ),
        migrations.AddField(
            model_name="orderrequest",
            name="admin_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="orderrequest",
            index=models.Index(fields=["order_code"], name="project_app_order_code_idx"),
        ),
        migrations.RunPython(
            _populate_order_codes,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="orderrequest",
            name="order_code",
            field=models.CharField(default=generate_order_code, editable=False, max_length=18, unique=True),
        ),
    ]
