# Generated by Django 6.1.1 on 2026-09-14 20:50

import project_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0013_orderrequest_payment_and_approval'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='orderrequest',
            name='project_app_order_code_idx',
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='order_code',
            field=models.CharField(default=project_app.models.generate_order_code, editable=False, max_length=18, unique=True),
        ),
    ]
